In [152]:
import pandas as pd
import sqlite3

# Loading the data
df = pd.read_csv("../data/TMDB_movie_dataset_v11.csv")

#let us see what we got!
df.head(10)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
5,293660,Deadpool,7.606,28894,Released,2016-02-09,783100000,108,False,/en971MEXui9diirXlogOrPKmsEn.jpg,...,Deadpool,The origin story of former Special Forces oper...,72.735,/zq8Cl3PNIDGU3iWNRoc5nEZ6pCe.jpg,Witness the beginning of a happy ending.,"Action, Adventure, Comedy","20th Century Fox, The Donners' Company, Genre ...",United States of America,English,"superhero, anti hero, mercenary, based on comi..."
6,299536,Avengers: Infinity War,8.255,27713,Released,2018-04-25,2052415039,149,False,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,...,Avengers: Infinity War,As the Avengers and their allies have continue...,154.340,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,An entire universe. Once and for all.,"Adventure, Action, Science Fiction",Marvel Studios,United States of America,"English, Xhosa","sacrifice, magic, superhero, based on comic, s..."
7,550,Fight Club,8.438,27238,Released,1999-10-15,100853753,139,False,/hZkgoQYus5vegHoetLkCJzb17zJ.jpg,...,Fight Club,A ticking-time-bomb insomniac and a slippery s...,69.498,/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg,Mischief. Mayhem. Soap.,Drama,"Regency Enterprises, Fox 2000 Pictures, Taurus...",United States of America,English,"dual identity, rage and hate, based on novel o..."
8,118340,Guardians of the Galaxy,7.906,26638,Released,2014-07-30,772776600,121,False,/uLtVbjvS1O7gXL8lUOwsFOH4man.jpg,...,Guardians of the Galaxy,"Light years from Earth, 26 years after being a...",33.255,/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg,All heroes start somewhere.,"Action, Science Fiction, Adventure",Marvel Studios,United States of America,English,"spacecraft, based on comic, space, orphan, adv..."
9,680,Pulp Fiction,8.488,25893,Released,1994-09-10,213900000,154,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,...,Pulp Fiction,"A burger-loving hit man, his philosophical par...",74.862,/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg,Just because you are a character doesn't mean ...,"Thriller, Crime","Miramax, A Band Apart, Jersey Films",United States of America,"English, Spanish, French","drug dealer, boxer, massage, stolen money, bri..."

In [12]:
#so there are a lot of data! 
df.shape

(1356719, 24)

In [14]:
#what kind of columns do we have:
df.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'keywords'],
      dtype='object')

In [16]:
#what type do they have
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1356719 entries, 0 to 1356718
Data columns (total 24 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   id                    1356719 non-null  int64
 1   title                 1356701 non-null  object
 2   vote_average          1356719 non-null  float64
 3   vote_count            1356719 non-null  int64
 4   status                1356719 non-null  object
 5   release_date          1072227 non-null  object
 6   revenue               1356719 non-null  int64
 7   runtime               1356719 non-null  int64
 8   adult                 1356719 non-null  bool
 9   backdrop_path         341915 non-null   object
 10  budget                1356719 non-null  int64
 11  homepage              140296 non-null   object
 12  imdb_id               653769 non-null   object
 13  original_language     1356719 non-null  object
 14  original_title        1356701 non-null  object
 15  overview              1050629 non-null  object
 16  popularity            1356719 non-null  float64
 17  poster_path           886765 non-null   object
 18  tagline               188818 non-null   object
 19  genres                770511 non-null   object
 20  production_companies  584945 non-null   object
 21  production_countries  711337 non-null   object
 22  spoken_languages      736438 non-null   object
 23  keywords              341279 non-null   object
dtypes: bool(1), float64(2), int64(5), object(16)
memory usage: 239.4+ MB

In [153]:
#lets begin by taking what we think its important
movies = df[[
    "id",
    "title",
    "release_date",
    "genres",
    "original_language",
    "popularity",
    "vote_average",
    "vote_count",
    "budget",
    "revenue",
    "runtime",
    "spoken_languages"
]].copy()

movies.head()

,id,title,release_date,genres,original_language,popularity,vote_average,vote_count,budget,revenue,runtime,spoken_languages
0,27205,Inception,2010-07-15,"Action, Science Fiction, Adventure",en,83.952,8.364,34495,160000000,825532764,148,"English, French, Japanese, Swahili"
1,157336,Interstellar,2014-11-05,"Adventure, Drama, Science Fiction",en,140.241,8.417,32571,165000000,701729206,169,English
2,155,The Dark Knight,2008-07-16,"Drama, Action, Crime, Thriller",en,130.643,8.512,30619,185000000,1004558444,152,"English, Mandarin"
3,19995,Avatar,2009-12-15,"Action, Adventure, Fantasy, Science Fiction",en,79.932,7.573,29815,237000000,2923706026,162,"English, Spanish"
4,24428,The Avengers,2012-04-25,"Science Fiction, Action, Adventure",en,98.082,7.710,29166,220000000,1518815515,143,"English, Hindi, Russian"

In [156]:
#and now the database itself
conn = sqlite3.connect("movies.db")
movies.to_sql("movies", conn, if_exists="replace", index=False)

1356719

In [26]:
#lets begin querying :D
#i want to see the Top 10 highest rated movies (min 500 votes)

query = """
        SELECT title, popularity, vote_average
        from movies
        where vote_count > 500
        order by vote_average DESC
        LIMIT 10;
"""
df = pd.read_sql(query,conn)
display(df)

                         title  popularity  vote_average
0                The Godfather     158.448         8.707
1     The Shawshank Redemption     122.610         8.702
2        The Godfather Part II      64.753         8.591
3             Schindler's List      65.084         8.573
4  Dilwale Dulhania Le Jayenge      33.575         8.552
5                 12 Angry Men      51.201         8.540
6                Spirited Away      68.024         8.539
7                     Parasite      64.627         8.515
8                   Your Name.      68.999         8.514
9              The Dark Knight     130.643         8.512

In [238]:
#another one! 
#I want to see how many different language exist in the db
query = """
            SELECT title, original_language,popularity, count(original_language)
            from movies
            group by original_language
            order by popularity DESC


"""

df = pd.read_sql(query,conn)
display(df)

,title,original_language,popularity,count(original_language)
0,Jagun Jagun,yo,206.348,55
1,Sisu,fi,157.379,3686
2,Sniper: The White Raven,uk,110.510,3419
3,Inception,en,83.952,739478
4,Spirited Away,ja,68.024,60460
...,...,...,...,...
172,The Legend of Kava Tonga,to,0.000,8
173,Zegedam,ti,0.000,12
174,Njengo'Thando,nr,0.000,1
175,O Clube da luta,ia,0.000,4
176,Mywaba,aa,0.000,2

In [236]:
#top 10 popular movies?
#don't search 3rd most popular movie...!
query ="""
    SELECT title, popularity, original_language, genres
    from Movies
    order by popularity DESC
    LIMIT 10

"""
df = pd.read_sql(query,conn)
display(df)

,title,popularity,original_language,genres
0,Blue Beetle,2994.357,en,"Action, Science Fiction, Adventure"
1,Gran Turismo,2680.593,en,"Action, Drama, Adventure"
2,A Female Boss with Big Tits and Her Cherry Boy...,2020.286,ja,Drama
3,The Nun II,1692.778,en,"Horror, Mystery, Thriller"
4,Meg 2: The Trench,1567.273,en,"Action, Science Fiction, Horror"
5,Retribution,1547.220,en,"Action, Mystery, Thriller, Crime"
6,Talk to Me,1458.514,en,"Horror, Thriller"
7,Fast X,1175.267,en,"Action, Crime, Thriller"
8,Sound of Freedom,1111.036,en,"Action, Drama"
9,Barbie,1069.340,en,"Comedy, Adventure, Fantasy"

In [62]:
#movies with highest budget
query = """

        SELECT title, budget
        from movies
        order by budget DESC
        limit 10


"""
df = pd.read_sql(query,conn)
display(df)

                                           title     budget
0                                 In Whose Name?  999999999
1  ryan gosling der sutter logan pauls tissemand  900000000
2                                           Enea  888000000
3                     ETERNIA: TWILIGHT OF STARS  873000000
4                        Adventures in Bora Bora  800000000
5                            Shadow the Hedgehog  800000000
6                      M4's The Hobbit Book Edit  700000000
7                                         Крик 4  645654654
8        Playmobil The Movie 2: Maximus' Revenge  600000000
9                                       Avatar 5  600000000

In [72]:
#movies with the highest revenue
query = """

        SELECT title, revenue
        from movies
        order by revenue DESC
        limit 10


"""
df = pd.read_sql(query,conn)
display(df)

                                               title     revenue
0  Juliet and Romeo - 1231 ☆*: .｡. o(≧▽≦)o .｡.:*☆...  4999999999
1                                  babben: the movie  4999999999
2                                 Macbeth's Ambition  3477779998
3                                  TikTok Rizz Party  3000000000
4                            Adventures in Bora Bora  3000000000
5                                          Bee Movie  2930000000
6                                             Avatar  2923706026
7                          M4's The Hobbit Book Edit  2914620020
8                                  Avengers: Endgame  2800000000
9                           Avatar: The Way of Water  2320250281

In [74]:
#movies longer than 3 hours
query = """


    SELECT title, runtime
    FROM movies
    WHERE runtime > 180
    ORDER BY runtime DESC;

    
"""
df = pd.read_sql(query,conn)
display(df)

                                                   title  runtime
0                                   Modern Times Forever    14400
1                             Svalbard minutt for minutt    13319
2                                              Cinématon    12480
3                                           Beijing 2003     9000
4                                Untitled #125 (Hickory)     7200
...                                                  ...      ...
20201                                    Big Naturals 52      181
20202                                       Дочки-матери      181
20203                                       Mom Is Horny      181
20204                                     Cock Starved 2      181
20205  The Tables Are Being Turned In This Mid-Summer...      181

[20206 rows x 2 columns]

In [146]:
#Average rating per language

query = """

            SELECT  original_language, round(vote_average) as average_rating_per_language
            from movies
            WHERE vote_average BETWEEN 1 AND 9.9
            group by original_language
            order by average_rating_per_language DESC
           
            

"""
df = pd.read_sql(query,conn)
display(df)

   original_language  average_rating_per_language
0                 ty                          9.0
1                 ko                          9.0
2                 ja                          9.0
3                 hi                          9.0
4                 zu                          8.0
5                 wo                          8.0
6                 ur                          8.0
7                 uk                          8.0
8                 tr                          8.0
9                 te                          8.0
10                sv                          8.0
11                sk                          8.0
12                sh                          8.0
13                ru                          8.0
14                ro                          8.0
15                pt                          8.0
16                oc                          8.0
17                ms                          8.0
18                mk                          8.0
19                kw                          8.0
20                ku                          8.0
21                it                          8.0
22                ie                          8.0
23                hr                          8.0
24                he                          8.0
25                gl                          8.0
26                ga                          8.0
27                fr                          8.0
28                fi                          8.0
29                fa                          8.0
30                et                          8.0
31                es                          8.0
32                en                          8.0
33                de                          8.0
34                da                          8.0
35                cn                          8.0
36                bn                          8.0
37                ba                          8.0
38                ay                          8.0
39                ar                          8.0
40                ab                          8.0
41                zh                          7.0
42                xx                          7.0
43                vi                          7.0
44                tn                          7.0
45                tk                          7.0
46                th                          7.0
47                ta                          7.0
48                sw                          7.0
49                su                          7.0

In [106]:
#Average runtime per language

query = """
            SELECT original_language, round(runtime) as average_runtime_per_language
            from movies
            group by original_language
            order by average_runtime_per_language desc
            limit 10

"""


df = pd.read_sql(query,conn)
display(df)

  original_language  average_runtime_per_language
0                sd                         239.0
1                hi                         190.0
2                te                         186.0
3                iu                         172.0
4                ru                         162.0
5                ml                         158.0
6                kn                         156.0
7                kk                         156.0
8                de                         156.0
9                ta                         155.0

In [142]:
#Average rating in greek movies
query = """
            SELECT ROUND(AVG(vote_average), 2) AS avg_greek_rating
            FROM movies
            WHERE original_language = 'el' AND vote_average BETWEEN 1 AND 9.9


"""


df = pd.read_sql(query,conn)
display(df)

   avg_greek_rating
0              5.47

In [164]:
#Average rating in english spoken movies


query = """
            SELECT ROUND(AVG(vote_average), 2) AS avg_en_rating
            FROM movies
            WHERE spoken_languages = 'English' AND vote_average BETWEEN 1 AND 9.9


"""


df = pd.read_sql(query,conn)
display(df)

   avg_en_rating
0           5.87

In [266]:
#Query 10: Movies released per day
query = """
SELECT release_date, COUNT(*) AS movie_count
        FROM movies
        WHERE release_date IS NOT NULL AND release_date < '2026-01-01'
        GROUP BY release_date
        ORDER BY release_date DESC
        """

df = pd.read_sql(query,conn)
display(df)

      release_date  movie_count
0       2025-12-31          149
1       2025-12-30           57
2       2025-12-29           31
3       2025-12-28           43
4       2025-12-27           62
...            ...          ...
43033   1867-01-01            1
43034   1865-01-01            3
43035   1837-10-29            1
43036   1800-09-11            1
43037   1800-01-01            2

[43038 rows x 2 columns]

In [264]:
#Movies per year

query = """
SELECT SUBSTR(release_date,1,4)as year, COUNT(*) AS movie_count
    FROM movies
    WHERE SUBSTR(release_date,1,4) IS NOT NULL AND release_date < 2027
    GROUP BY year
    ORDER BY year DESC
 

"""

df = pd.read_sql(query,conn)
display(df)

     year  movie_count
0    2026         1919
1    2025        36383
2    2024        39598
3    2023        49449
4    2022        48135
..    ...          ...
145  1874            1
146  1867            2
147  1865            3
148  1837            1
149  1800            3

[150 rows x 2 columns]

In [188]:
#Most common genres
query = """
            SELECT genres, COUNT(*) AS count
            FROM movies
            GROUP BY genres
            ORDER BY count DESC
            LIMIT 10;
"""


df = pd.read_sql(query,conn)
display(df)

           genres   count
0            None  586208
1     Documentary  156547
2           Drama  119962
3          Comedy   64665
4       Animation   35789
5           Music   28981
6          Horror   25838
7  Drama, Romance   11667
8   Comedy, Drama   10582
9         Romance    9232

In [200]:

#50 Movies with very high rating but low popularity (hidden gems)
query = """
        
        SELECT title, vote_average, popularity
        FROM movies
        WHERE vote_average BETWEEN 1 AND 9.9 AND popularity < 10
        ORDER BY vote_average DESC
        LIMIT 50

"""
df = pd.read_sql(query,conn)
display(df)

,title,vote_average,popularity
0,"What's New, Scooby-Doo? Vol. 1: Space Ape at t...",9.900,2.832
1,"What's New, Scooby-Doo? Vol. 5: Sports Spookta...",9.900,3.630
2,Scooby-Doo: Mystery in Motion,9.900,4.145
3,Cartoon Network Christmas: Yuletide Follies,9.900,2.508
4,Scooby-Doo's Spookiest Tales,9.900,3.367
5,Kjarval and The Door Mountain,9.900,0.600
6,Tatiana,9.900,2.246
7,Prologue,9.900,1.439
8,The Anal Virgin,9.900,0.861
9,Z,9.875,0.600
10,"What's New, Scooby-Doo? Vol. 7: Ghosts on the Go!",9.872,2.675
11,"Firenze, canzone triste (Volume I)",9.833,0.000
12,Monster Planet of Godzilla,9.833,1.400
13,WWE: The Spectacular Legacy of the AWA,9.833,1.284
14,David Guetta - Live at iTunes Festival 2014,9.833,0.710
15,#1,9.833,0.600
16,Music is on the Menu: Sofía Carson,9.833,3.431
17,Scooby-Doo! and the Sea Monsters,9.800,3.452
18,Linkin Park and Friends - Celebrate Life in Ho...,9.800,3.225
19,Bubble Guppies: Animals Everywhere,9.800,2.085
20,Bubble Guppies,9.800,2.169
21,Vanessa da Mata: Caixinha de Música Ao Vivo,9.800,0.942
22,Lottie Dottie Chicken,9.800,1.715
23,Sandy & Junior: Nossa História,9.800,1.264
24,BABYMETAL - Live at Wembley,9.800,0.655
25,Untitled (For Derek Jarman),9.800,1.400
26,Kamasutra for Gay Men,9.800,4.272
27,The Faces of Alice,9.800,1.843
28,The Tragically Hip - A National Celebration,9.800,0.600
29,Away From Home - The Global Streaming Event,9.800,0.812
30,The Daily Commute,9.800,0.600
31,Rajesh Khanna Superhits: Yeh Reshmi Zulfein,9.800,0.600
32,BABYMETAL - Live at Tokyo Dome: Black Night - ...,9.800,0.748
33,Casey Kasem's Rock 'n' Roll Goldmine: The Soul...,9.800,1.147
34,Gawr Gura 3D Live,9.800,0.600
35,Disney Sing-Along-Songs: The Lion King - Circl...,9.800,0.741
36,Alter Bridge - Live at the Royal Albert Hall (...,9.800,1.745
37,P.O.V. Punx 12: Tig Ol' Bitties,9.800,0.600
38,Ariana Marie: A Little Bit Harder,9.800,2.846
39,The Greatest Raid of All Time,9.800,1.988
40,Die Ärzte: Rock'n'Roll Realschule,9.800,0.747
41,Sioux Rapids,9.800,0.778
42,Games,9.800,0.600
43,The Love Club,9.800,0.600
44,Tux and Fanny,9.800,0.728
45,David Guetta - Live at iTunes Festival 2012,9.800,0.715
46,Luccas Neto em: Um Natal Muito Atrapalhado,9.800,0.986
47,Falas Negras,9.800,0.665
48,Katatonia: Last Fair Day Gone Night,9.800,1.214
49,Monsters of Cock 75,9.800,0.713

In [230]:
# Average revenue by language

query = """
        SELECT original_language, ROUND(AVG(revenue), 0)/1000000 AS avg_revenue_in_M
        FROM movies
        WHERE revenue > 0
        GROUP BY original_language
        ORDER BY avg_revenue_in_M DESC

        """

df = pd.read_sql(query,conn)
display(df)

   original_language  avg_revenue_in_M
0                 la       2501.220239
1                 az        120.154807
2                 af         85.384748
3                 he         64.128951
4                 en         49.925958
..               ...               ...
90                as          0.000300
91                ab          0.000234
92                sa          0.000100
93                kk          0.000006
94                my          0.000004

[95 rows x 2 columns]

In [234]:
# Movies with best revenue-to-budget ratio

query = """
        
SELECT title, budget, revenue,
       ROUND(1.0 * revenue / budget, 2) AS roi
FROM movies
WHERE budget > 100000 AND revenue > 0
ORDER BY roi DESC
LIMIT 10;

"""

df = pd.read_sql(query,conn)
display(df)

                                     title   budget     revenue      roi
0                                 The Park   500000  1000000000  2000.00
1  La razon de cada parte(Jose curricular)   500000  1000000000  2000.00
2                                      100   150000   150000000  1000.00
3                         KUCHAR x CLINTON  1000000  1000000000  1000.00
4                                 Chiikawa  1000000   923847923   923.85
5                                  Vacancy  1000000   903400045   903.40
6                      Paranormal Activity   215000   193355800   899.33
7                          Ahmad's Revenge   130000   100000000   769.23
8                        Lady Frankenstein   200000   139683000   698.41
9  The World of the Pharaoh (Live Theatre)  1000000   500000000   500.00

In [242]:
#Biggest Box Office flops

query = """
    SELECT title, budget, revenue, (revenue - budget) AS loss
    FROM movies
    WHERE budget > 0 AND revenue > 0
    ORDER BY loss ASC
    LIMIT 10;

"""

df = pd.read_sql(query,conn)
display(df)

,title,budget,revenue,loss
0,ryan gosling der sutter logan pauls tissemand,900000000,16,-899999984
1,Playmobil The Movie 2: Maximus' Revenge,600000000,22388764,-577611236
2,moose movie 2,470000000,1,-469999999
3,Guy with a Gorilla,450000000,2,-449999998
4,Diggy and The Bandits,447000000,12,-446999988
5,Diggy and The Bandits,447000000,12,-446999988
6,Les Schtroumpfs et l'abominable créature des n...,300000000,300,-299999700
7,Now That's What I Call Staxus! 2,288760000,3,-288759997
8,The Turkish Quandale Dingle Revolutions,250000000,5,-249999995
9,Star Wars: The Acolyte,230100000,46,-230099954